lol-duo/LoLDuoApi

src/main/java/com/lolduo/duo/service/RiotService.java

[FIX] log delete

---

src/main/java/com/lolduo/duo/entity/gameInfo/DuoEntity.java
src/main/java/com/lolduo/duo/entity/gameInfo/QuintetEntity.java
src/main/java/com/lolduo/duo/entity/gameInfo/SoloEntity.java
src/main/java/com/lolduo/duo/entity/gameInfo/TrioEntity.java
src/main/java/com/lolduo/duo/repository/TeamRepository.java
src/main/java/com/lolduo/duo/repository/gameInfo/DuoRepository.java
src/main/java/com/lolduo/duo/repository/gameInfo/QuintetRepository.java
src/main/java/com/lolduo/duo/repository/gameInfo/SoloRepository.java
src/main/java/com/lolduo/duo/repository/gameInfo/TrioRepository.java
src/main/java/com/lolduo/duo/service/RiotService.java

[Style] name changed :
1. team 엔티티 및 리포지토리 이름변경
2. 안어울리는 변수 이름 변경 (champion -> championId)
3. solo,duo,trio,quinetet Entity 및repository용 폴더 생성(gameInfo 라는 폴더)
4. @imygnam 이 작석했던 setDuo() 삭제.
5. DB에 기본적으로 setting해주는 함수들(setItem,setSpell 등) 위치만 아래로 내림

[Style] name changed

---

scripts/deploy.sh
src/main/java/com/lolduo/duo/service/RiotService.java

deploy.sh 파일 수정하여 CI/CD 될 때 datadog tracer 같이 실행되게 변경
라이엇 키 최신화

[FEAT] APM 추가 후, deploy.sh 수정 및 라이엇 키 최신화

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/dto/client/ChampionInfoDTO.java
src/main/java/com/lolduo/duo/dto/client/ChampionInfoDTOList.java
src/main/java/com/lolduo/duo/entity/ChampionEntity.java
src/main/java/com/lolduo/duo/repository/gameInfo/DuoRepository.java
src/main/java/com/lolduo/duo/repository/gameInfo/SoloRepository.java
src/main/java/com/lolduo/duo/service/ClientService.java
src/main/java/com/lolduo/duo/service/RiotService.java
src/main/resources/application.yml

[FEAT] getChampionList 추가
soloInfo 가져올 수 있음.

[FEAT] getChampionList 추가

---

src/main/resources/application.yml

[FEAT] username 추가

---

src/main/resources/application.yml

[FIX] username 삭제

---

src/main/java/com/lolduo/duo/service/SlackNotifyService.java

서버 구동 시 프론트 페이지, 스웨거, 데이터 독 링크 추가, 서버 종료 시 데이터 독 링크 추가

[FEAT] 슬랙 알림 봇 메시지에 정보 추가

---

src/main/java/com/lolduo/duo/dto/client/ClinetChampionInfoDTO.java
src/main/java/com/lolduo/duo/service/ClientService.java

position url 리턴값 null 나오는 것 수정.

[Fix] position url : null issue

---

src/main/java/com/lolduo/duo/service/ClientService.java

[FIX] 없는 행 검색 시 ClienChampiontInfoList 비어있는 문제 해결

---

src/main/java/com/lolduo/duo/repository/clientInfo/DuoInfoRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/ICombinationInfoRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/QuintetInfoRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/TrioInfoRepository.java
src/main/java/com/lolduo/duo/service/ClientService.java
src/main/java/com/lolduo/duo/service/RiotService.java
src/main/resources/application.yml

[FIX] ?챔피언에 지정한 포지션을 다른 포지션에서 사용 못하게 하는 기능 구현 방법 변경

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/object/dto/client/ChampionInfoDTO.java
src/main/java/com/lolduo/duo/object/entity/ChampionEntity.java
src/main/java/com/lolduo/duo/object/response/sub/ChampionInfo.java

[Feature] swagger example 추가

---

src/main/java/com/lolduo/duo/object/response/sub/ChampionInfo.java
src/main/java/com/lolduo/duo/service/ClientService.java

https://ajwquestion.atlassian.net/browse/DAM-101?atlOrigin=eyJpIjoiY2JhMjM2MzU2MmFmNDU1NjgzMDhkZmE2OGYxZGRkNzIiLCJwIjoiaiJ9
*두 하위 이슈가 모두 수정되어야 신택스 에러가 발생하지 않기 때문에 두 개를 하나의 커밋으로 수정함.

[FEAT] 반환 class에 id 추가하기 & 함수에 id 연결해서 내려보내주기

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/object/entity/ChampionEntity.java
src/main/java/com/lolduo/duo/object/response/getChampionList/Champion.java
src/main/java/com/lolduo/duo/service/ClientService.java

[Feature] DAM-99/ 챔피언 리스트 리턴할때 영어도 추가

---

src/main/java/com/lolduo/duo/service/ClientService.java

api 문제인인지 확인, datadog 로그에 
클라이언트에서 값 요청시 포지션값이 null로 들어오는것이 확인되어,
잘못된 요청인지를 확인하는 코드 추가.

[fix] api 문제인인지 확인

---

src/main/java/com/lolduo/duo/service/ClientService.java

[fix] api 문제인인지 확인 관련 로그 추가

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/service/ClientService.java

https://ajwquestion.atlassian.net/browse/DAM-104?atlOrigin=eyJpIjoiNGY4ZDFjMzgxZmNjNDRlY2ExNDU0OWJmZjMwZjgwZjAiLCJwIjoiaiJ9

[FEAT] API 시간 측정 로그 추가

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent.java
src/main/java/com/lolduo/duo/service/ClientService.java
src/main/resources/application.yml

https://ajwquestion.atlassian.net/browse/DAM-116?atlOrigin=eyJpIjoiMmU4YmYyYTZhZDNkNGM4MDhlMDU5ZjhkNDhmMWIwM2EiLCJwIjoiaiJ9
* DAM-119는 아직 미해결

[FIX] 조합 상세 페이지에서 아이템 3개씩만 나오게 하기 & X 삭제 & 아이템 더미 데이터 삭제

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent.java

https://ajwquestion.atlassian.net/browse/DAM-119?atlOrigin=eyJpIjoiNjkzNjA3ZjE1MzdkNDVhOGFhMGZiOTJhOTZiMDIwMjgiLCJwIjoiaiJ9

[FIX] 조합 요약 페이지에서 앞 아이템 3개가 같은 아이템 조합을 같은 행으로 취급함

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent.java

https://ajwquestion.atlassian.net/browse/DAM-121?atlOrigin=eyJpIjoiMDRiYjAxMGM5Y2RkNGJkYjgwMjIzOGY1MDk0Mjk2ODYiLCJwIjoiaiJ9

[FIX] 아이템 조합 중 [0, 0, 0]이 존재하는 조합은 반환 결과에서 제외

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent.java

https://ajwquestion.atlassian.net/browse/DAM-123?atlOrigin=eyJpIjoiZmU5YTdlMmEwN2VkNDdjNzgzZGNmNGM1YjM5OGE4YzEiLCJwIjoiaiJ9

[FIX] 메인 룬과 서브 룬이 중복되는 현상 수정 & 룬 조합 정보 2개 이하일 때 더미 데이터 추가하는 코드 삭제

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent.java

https://ajwquestion.atlassian.net/browse/DAM-137?atlOrigin=eyJpIjoiNTI3MWVhYjIzY2Q0NGNhZjgwOTdkNzBjY2IzMzE0MzUiLCJwIjoiaiJ9

[FIX] 조합 상세 페이지-요약 페이지에서 아이템 개수 3개 이상인 템 조합만 보여줌

---

.github/workflows/awsBuild.yml
.github/workflows/awsDevBuild.yml

https://ajwquestion.atlassian.net/browse/DAM-146?atlOrigin=eyJpIjoiNzg0ODFlOGU4ZDgzNDBlMDkzMjMzNTlmODBmM2ExY2IiLCJwIjoiaiJ9

[FEAT] Github Action 완료 시 슬랙 알림 기능 추가

---

src/main/java/com/lolduo/duo/repository/clientInfo/DoubleCombiRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/ICombiRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/PentaCombiRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/SoloCombiRepository.java
src/main/java/com/lolduo/duo/repository/clientInfo/TripleCombiRepository.java
src/main/java/com/lolduo/duo/service/ClientService.java
src/main/resources/application.yml

https://ajwquestion.atlassian.net/browse/DAM-148?atlOrigin=eyJpIjoiMzg3OGIzYzU5NDdmNDFkMWI0ZjhmMTc3ODgwMWE5MTMiLCJwIjoiaiJ9

[FEAT] 챔피언 조합 검색 페이지에서 같은 챔피언-포지션이면 perk_myth_item 달라도 하나로 묶어서 보내기

---

src/main/java/com/lolduo/duo/service/ChampionDetailComponent2.java
src/main/java/com/lolduo/duo/service/temp/PerkUrlMap.java

[FEATURE] DAM-143 / perk active되는것 추가.

---

src/main/java/com/lolduo/duo/object/response/championDetail2/ResponseInfo.java
src/main/java/com/lolduo/duo/service/ChampionDetailComponent2.java
src/main/java/com/lolduo/duo/service/ClientService.java

[FIX] championName 추가, 및 allCount,winCount수정

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/service/HealthCheckService.java

로드 밸런서에서 헬스 체크를 하기 위한 API와 서비스 추가

[FEAT] 헬스 체크 API, 서비스 추가

---

scripts/deploy.sh
src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/service/ClinetServiceV2.java
src/main/resources/logback-spring.xml

yml 파일수정
datadog 제거
response 타입 수정

Api version2

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/service/ClinetServiceV2.java

[FEAT][API_V2] getInfoV2/Solo API 추가

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/object/response/v2/SoloResponseV2.java
src/main/java/com/lolduo/duo/repository/v2/SoloMatchRepository.java
src/main/java/com/lolduo/duo/service/ClientServiceV2.java

[FEAT][API_V2] getInfoV2/Solo API Get으로 수정

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/v2/ClientServiceV2.java

404 조건 추가.
컨트롤러에 getDoubleChampionInfoList  함수 적용.

[FEAT][API_V2] getDoubleChampionInfoList 함수 추가.

---

src/main/java/com/lolduo/duo/v2/ClientServiceV2.java
src/main/java/com/lolduo/duo/v2/response/ChampionResponse.java

[FIX][API_V2] Cannot call sendError() FIX

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/v2/ClientServiceV2.java
src/main/java/com/lolduo/duo/v2/entity/detail/ItemCombEntity.java
src/main/java/com/lolduo/duo/v2/entity/detail/RuneCombEntity.java
src/main/java/com/lolduo/duo/v2/entity/detail/SoloChampionCombEntity.java
src/main/java/com/lolduo/duo/v2/entity/detail/SoloMatchDetailEntity.java
src/main/java/com/lolduo/duo/v2/entity/detail/SpellCombEntity.java
src/main/java/com/lolduo/duo/v2/repository/detail/ItemCombRepository.java
src/main/java/com/lolduo/duo/v2/repository/detail/RuneCombRepository.java
src/main/java/com/lolduo/duo/v2/repository/detail/SoloChampionCombRepository.java
src/main/java/com/lolduo/duo/v2/repository/detail/SoloMatchDetailRepository.java
src/main/java/com/lolduo/duo/v2/repository/detail/SpellCombRepository.java
src/main/java/com/lolduo/duo/v2/response/mainPage/DoubleResponseV2.java
src/main/java/com/lolduo/duo/v2/response/mainPage/SoloResponseV2.java

getSoloChampionInfoList
String  rankChangeNumber -> int rankChangeNumber
getDoubleChampionInfoList 
String rankChangeNumber -> int rankChangeNumber

[FEAT][API_V2] getSoloChampionInfoList, getDoubleChampionInfoList 필드수정

---

src/main/java/com/lolduo/duo/v2/ClientServiceV2.java
src/main/java/com/lolduo/duo/v2/response/mainPage/DoubleResponseV2.java
src/main/java/com/lolduo/duo/v2/response/mainPage/SoloResponseV2.java

DoubleResponseV2, SoloResponseV2 
rankChangeNumber필드 타입 수정 (String -> Long)
rankChangeColor 필드 값 삭제.

[FEAT][API_V2] DoubleResponseV2 필드 값 수정.

---

src/main/resources/logback-spring.xml

[FEAT][API_V2] logback-spring.xml 수정

---

.github/workflows/awsBuild.yml
build.gradle

[FEAT][API_V2] jdk version 17 -> 8

---

src/main/java/com/lolduo/duo/service/slack/SlackNotifyService.java

[FEAT][API_V2] var error fix

---

.github/workflows/awsBuild.yml
build.gradle
scripts/deploy.sh

[FEAT][API_V2] deploy.sh 수정 JDK 17으로 변경

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/v2/entity/front/DoubleMatchFrontEntity.java
src/main/java/com/lolduo/duo/v2/entity/front/SoloMatchFrontEntity.java

[FIX][API_V2] /v2/doubleInfo 주석처리 해제

---

src/main/java/com/lolduo/duo/response/championDetail/sub/DetailChampionComp.java

Detail Response Filed Name Changed

[FIX][API_V2] Detail Response Filed Name Changed

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/entity/front/DoubleMatchFrontEntity.java
src/main/java/com/lolduo/duo/entity/front/SoloMatchFrontEntity.java
src/main/java/com/lolduo/duo/repository/front/DoubleMatchFrontRepository.java
src/main/java/com/lolduo/duo/repository/front/SoloMatchFrontRepository.java
src/main/java/com/lolduo/duo/service/ClientServiceV2.java

Front table done

---

src/main/java/com/lolduo/duo/service/DetailService.java

[FIX][API_V2] getSoloChampionDetail log 추가

---

src/main/java/com/lolduo/duo/controller/ClientApi.java
src/main/java/com/lolduo/duo/parser/EntityToResponseParser.java
src/main/java/com/lolduo/duo/service/DetailService.java

SoloMatchDetail List 관련 log 안찍히는 문제 수정

[FIX][API_V2] SoloMatchDetail List 관련 log 안찍히는 문제 수정

---

src/main/java/com/lolduo/duo/parser/EntityToResponseParser.java
src/main/java/com/lolduo/duo/service/ClientServiceV2.java

Detail API mainRune 안나오는 문제 수정

[FIX][API_V2] Detail API mainRune 안나오는 문제 수정

---

src/main/java/com/lolduo/duo/service/ClientServiceV2.java

request ,response 순서 다른 이슈 fix

[FIX][API_V2] request ,response 순서 다른 이슈 fix
